"""empty message

Revision ID: 1ca0a93ec36d
Revises: 3c75e1e8f198
Create Date: 2020-03-20 23:43:42.864641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca0a93ec36d'
down_revision = '3c75e1e8f198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'likes')
    # ### end Alembic commands ###
