"""empty message

Revision ID: 3c75e1e8f198
Revises: a2cc91e3f336
Create Date: 2020-03-20 22:58:49.108214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c75e1e8f198'
down_revision = 'a2cc91e3f336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_anonymous')
    # ### end Alembic commands ###
