"""empty message

Revision ID: e6d81f243ef4
Revises: 47d3222502d1
Create Date: 2020-03-18 19:57:15.263616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d81f243ef4'
down_revision = '47d3222502d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('liked_by', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'liked_by')
    # ### end Alembic commands ###
